### ISSUE TITLE
Ложные инструменты в портфеле

### ISSUE THREAD

**Issue by leodev87** [ya-erm/TTExtension#10]
Этого инструмента давно нет в портфеле, а он постоянно его показывает
![image](https://user-images.githubusercontent.com/2694255/98143692-7768e900-1eda-11eb-9c26-e5001eb33e97.png)
![image](https://user-images.githubusercontent.com/2694255/98143716-8059ba80-1eda-11eb-9ecd-13b075d7b3d1.png)

**Comment by ya-erm** [comment]
Рядом с ним при наведении появляется значок удаления? 
![image](https://user-images.githubusercontent.com/25526713/98146360-8ea8d600-1edc-11eb-9895-fe480dacb484.png)

**Comment by ya-erm** [comment]
Проверьте, воспроизводится ли эта ошибка в последней версии расширения?
