### ISSUE TITLE
Не учитывать валюту

### ISSUE THREAD

**Issue by beitan** [ya-erm/TTExtension#12]
Добавить в настройках возможность не учитывать в итогах валюту в колонках expected и fixed:

![image](https://user-images.githubusercontent.com/68656340/98909130-72a3c680-24d2-11eb-979c-61b3d18c8b12.png)

**Comment by ya-erm** [comment]
Реализовано в https://github.com/ya-erm/TTExtension/commit/6b56400d8515f0d01d57b7145df6ef7e2dc3f1fb.
Доступно начиная с версии 1.3.2
![exclude](https://user-images.githubusercontent.com/25526713/99077051-3608c580-25cd-11eb-84a4-6447f2ddcdc1.png)
