### ISSUE TITLE
Подсчет P&L за день (сессию)

### ISSUE THREAD

**Issue by beitan** [ya-erm/TTExtension#3]
Можно ли попросить добавить переключатель этой для фичи? Хорошо бы еще, чтобы результаты за сессию (с 10:00 до 02:00) отображались не только в порфолио, но и в статистике по конкретной бумаге

Спасибо за труды, расширение экономит много времени!

**Comment by ya-erm** [comment]
Уточните, Вам хотелось бы видеть **ожидаемую** прибыль за день (которую сейчас уже можно посмотреть в официальном мобильном приложении или веб-терминале), или речь идёт о **зафиксированной** прибыли?

**Comment by beitan** [comment]
Зафиксированной, конечно. Смысл в просмотре итога торгов для интрадей по акциям и результата в целом за день. Разделить как-то зафиксированную историческую P&L за все время и зафиксированную внутридневную. Будет удобно быстро оценить результаты дня, если совершено много операций внутри дня/сессии. (десятки, а то и сотни).

**Comment by ya-erm** [comment]
Идея хорошая, постараюсь сделать по возможности.

**Comment by ya-erm** [comment]
@beitan Реализовано в версии 1.2.4, если заметите какие-то ошибки, пожалуйста, отпишитесь
