### ISSUE TITLE
RDS.A

### ISSUE THREAD

**Issue by beitan** [ya-erm/TTExtension#6]
Нельзя просмотреть историю этой бумаги, отображает общий портфель, при клике на вкладку "RDS.A"

**Comment by ya-erm** [comment]
Спасибо за отчёт об ошибке, исправил (коммит https://github.com/ya-erm/TTExtension/commit/160eeaf1a6d80438cf97b7cc3dc98723e2909a68), теперь начиная с версии 1.2.5 вкладка истории сделок для тикера RDS.A и ему подобных должна открываться корректно
